### ISSUE TITLE
Whats the encoding of these files?

### ISSUE THREAD

**Issue by suned** [zhangdongxu/kbp37#1]
Ive been trying to reuse your data, but I cant seem to figure out the encoding of your files.
It seems like some combination of utf-8/cp1252/?

Can you give me a hint? :)

**Comment by zhangdongxu** [comment]
Sorry, there were a few noise strings that cannot be coded in utf-8. I just fixed this problem by removing them. The removed part took nearly 0.027% of previous version.

Thanks for letting me know. And if there are any other questions, please feel free to ask.

**Comment by suned** [comment]
It looks great now, thanks!
